### ISSUE TITLE
Create a dedicated EBS CSI storage class

### ISSUE THREAD

**Issue by christian-roggia** [noi-techpark/odh-infrastructure-v2#53]
A new storage class is required in the cluster with `provisioner: ebs.csi.aws.com` in order to take advantage of the EBS CSI driver. See [this documentation link](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md) for more information.

We should also consider migrating the default storage class to the EBS CSI with `gp3` volume type. We should also verify how to migrate existing volumes to the new storage class and driver.

This is what we currently have online in the cluster (currently in use by all persistent volumes in the cluster):
```
➜  ~ kubectl get storageclasses.storage.k8s.io
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   202d
```

```yaml
# kubectl get storageclasses.storage.k8s.io gp2 -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
